osx_image: xcode10.1
language: objective-c
xcode_project: AlchemySwift.xcodeproj # path to your xcodeproj folder
xcode_scheme: AlchemySwift
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 7


  # Only if app has Carthage dependencies
  # - carthage bootstrap --verbose

script:
  - echo "Carthage: `carthage version`"
  - carthage build --no-skip-current
  - xcodebuild test -project AlchemySwift.xcodeproj -scheme AlchemySwift -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 7' | xcpretty --test --color
